- src/main/docs/guide/awsCredentialsProvider.adoc
- src/main/docs/guide/toc.yml
Please, let me know if this is not the use-case intended for `EnvironmentAWSCredentialsProvider`.
> Document EnvironmentAWSCredentialsProvider

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautRequestReader.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
> Request-level support for custom domains

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/model/bind/ContextArgumentBinder.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/EchoMicronautController.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
Ability to inject Lambda `Context` directly into the controller methods
> Argument binder for Lambda Context object

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
@graemerocher there is `@PendingFeature` to also support global `status` handlers but it goes beyond my current knowledge
> fixed global exception handling using @Error not working

- src/main/docs/guide/lambda.adoc
Changed from 'sayHello' to 'echo' to match the description after the source code.
> change the method name to match the description

- src/main/docs/guide/awsCredentialsProvider.adoc
- src/main/docs/guide/introduction.adoc
I made a few minor documentation updates I found while reading through it. I wasn't sure what the branching model is here, so I made a PR back to `master`. If that's wrong let me know and I'll follow whatever process you all are working with. Cheers!
> Minor documentation updates.

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
- function-aws-api-proxy/src/test/resources/static-lorem/lorem.txt
> API Proxy lambda handle static resource routing

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ResponseStatusSpec.groovy
> handing nulls and optionals as 404s

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ResponseStatusSpec.groovy
> void return method from the controller does not trigger 404

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
See: https://github.com/micronaut-projects/micronaut-aws/issues/128
> Constructor of MicronautRequestStreamHandler is public

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/CookiesSpec.groovy
Fixes #131 . Return empty list when missing.
> Fix for Issue #131 - support missing Cookie header

- examples/api-gateway-example/README.md
gradlew was written as graldew
> Update README.md fixing typo

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyResponse.java
> Introspecting subtypes of MutableHttpResponse

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- gradle.properties
> Resolving function name from the lambda Context (when available)

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
> Mutating container response when exceptions are produced.

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
Fix for https://github.com/micronaut-projects/micronaut-aws/issues/155 
this code is tested agains use cases and should work now.
> Fix - Type mismatch in stream condition for Bug #155

- aws-common/build.gradle
- function-aws-alexa/build.gradle
- function-aws-api-proxy/build.gradle
> Avoid leaking commons-logging and including jcl-over-slf4j

- aws-common/build.gradle
- build.gradle
- function-aws-alexa/build.gradle
- function-aws-alexa/src/main/java/io/micronaut/function/aws/alexa/AlexaConfiguration.java
- function-aws-api-proxy/build.gradle
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/AwsObjectMapperFactory.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyConfiguration.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyExceptionHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ObjectMapperListenerSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ObjectMapperSpec.groovy
- function-aws-custom-runtime/build.gradle
- function-aws/build.gradle
- function-aws/src/main/java/io/micronaut/function/aws/MicronautLambdaContext.java
- gradle.properties
- src/main/docs/guide/lambda/apiProxy.adoc
> Using a different ObjectMapper if configured to do so

- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/LambdaRuntimeInvocationResponseHeaders.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/MicronautLambdaRuntime.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/ReservedRuntimeEnvironmentVariables.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/RuntimeContext.java
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/MicronautLambdaRuntimeSpec.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/RuntimeContextSpec.groovy
@graemerocher I will have more changes about custom runtime but just to keep PRs small this is a more complete implementation of the RuntimeContext
> More complete RuntimeContext

- function-aws-alexa/src/main/java/io/micronaut/function/aws/alexa/handlers/AnnotatedRequestHandler.java
Close: https://github.com/micronaut-projects/micronaut-aws/issues/218
I've verified this works with Micronaut 2.0.0.M2
> fix: Don't use $AnnotationMetadata

- function-aws-alexa/build.gradle
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/AmazonDomain.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/AmazonEffect.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/AmazonEmotion.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/AmazonEmotionIntensity.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/BreakStrength.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/EmphasisLevel.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/InterpretAs.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/InterpretAsDateFormat.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/PhoneticAlphabet.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/ProsodyPitch.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/ProsodyRate.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/ProsodyVolume.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/Ssml.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/SupportedLang.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/Voice.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/WordRole.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/package-info.java
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/ssml/AmazonDomainSpec.groovy
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/ssml/AudioSpec.groovy
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/ssml/SsmlSpec.groovy
- src/main/docs/guide/alexa/ssmlbuilder.adoc
- src/main/docs/guide/toc.yml
see: https://github.com/micronaut-projects/micronaut-aws/issues/240
> feat: Add SSML builder

- function-aws-alexa/build.gradle
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/AlexaSkillBuilder.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/DefaultAlexaSkillBuilder.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/package-info.java
- function-aws-alexa/src/main/java/io/micronaut/function/aws/alexa/AlexaFunction.java
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/builders/AlexaSkillBuilderSpec.groovy
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/builders/ApplicationContextSpecification.groovy
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/builders/ConfigurationFixture.groovy
Extract AlexaSkill builder to its own class.
Close: https://github.com/micronaut-projects/micronaut-aws/issues/238
I am starting to move non-function related logic to package `io.micronaut.aws.alexa`.
> feat: register ResponseInterceptor in Alexa Skill

- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/flashbriefing/FlashBriefingItem.java
- function-aws-alexa/src/main/java/io/micronaut/aws/alexa/flashbriefing/package-info.java
- function-aws-alexa/src/test/groovy/io/micronaut/aws/alexa/flashbriefing/FlashBriefingItemSpec.groovy
See: https://github.com/micronaut-projects/micronaut-aws/issues/243
> feat: Add FlashBriefingItem

- src/main/docs/guide/corretto.adoc
- src/main/docs/guide/toc.yml
close: https://github.com/micronaut-projects/micronaut-aws/issues/242
> docs: Add corretto section

- aws-alexa/build.gradle
- aws-alexa/src/test/groovy/io/micronaut/aws/EmbeddedServerSpecification.groovy
- aws-alexa/src/test/groovy/io/micronaut/aws/alexa/flashbriefing/FlashBriefingControllerSpec.groovy
- aws-alexa/src/test/java/io/micronaut/aws/alexa/flashbriefing/FlashBriefingRepository.java
- aws-alexa/src/test/java/io/micronaut/aws/alexa/flashbriefing/FlashBriefingsController.java
- src/main/docs/guide/alexa/flashbriefings.adoc
- src/main/docs/guide/toc.yml
see: https://github.com/micronaut-projects/micronaut-aws/issues/243
> docs: flashbriefings docs

- src/main/docs/guide/alexa.adoc
- src/main/docs/guide/alexa/alexalambda.adoc
- src/main/docs/guide/alexa/ssmlbuilder.adoc
- src/main/docs/guide/alexa/webservice.adoc
- src/main/docs/guide/toc.yml
This documents the changes to alexa support.
> Improve alexa docs

- function-aws-alexa/src/main/java/io/micronaut/function/aws/alexa/AlexaFunction.java
- function-aws-alexa/src/test/groovy/io/micronaut/function/aws/alexa/RefreshInterceptorWorkAround.groovy
- function-aws-api-proxy/build.gradle
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ConsumesSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/CookiesSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FiltersSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FluxSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ParametersSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ResponseStatusSpec.groovy
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/DefaultRouterWorkAround.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/HelloWorldMicronautTest.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/IpPatternsRuleWorkaround.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/MicronautLambdaRuntime.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- function-aws/src/test/groovy/io/micronaut/function/aws/RefreshInterceptorWorkAround.groovy
- gradle.properties
- settings.gradle
Updates to Mircronaut 2.0 
Enables eager initialization of singletons for Lambda ApplicationContexts.
> Updates AWS module to to Micronaut 2.0.0 

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FiltersSpec.groovy
this should be the same behaviour as the Netty server is having
fixes #271
> always trigger the filters even the route is not found

- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfiguration.java
- aws-parameter-store/src/test/groovy/io/micronaut/discovery/aws/parameterstore/AWSPropertyStoreMockConfigurationClientSpec.groovy
PR resolves https://github.com/micronaut-projects/micronaut-aws/issues/376
> Disable System Manager Parameter Store queries by micronaut environment

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaHandler.java
In case a user wants to override it to add extra converters.
> Extra add converter method

- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterQueryProvider.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/DefaultParameterQueryProvider.java
This annotation is required for the new component to work. Sorry I missed this.
> Add missing @BootstrapContextCompatible declarations

- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyRequestAdapter.java
- function-aws-api-proxy-test/src/test/groovy/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServerSpec.groovy
Close: https://github.com/micronaut-projects/micronaut-aws/pull/763
> Fix request parameter gathering in AWS proxy adapter

- function-aws-api-proxy-test/build.gradle
see: https://github.com/micronaut-projects/micronaut-aws/issues/864
> build: pin jetty server to 9.4.35

- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/MicronautLambdaRuntime.java
Here the PR as suggested in #881
> Append cause to thrown exception.

- src/main/docs/guide/lambda/lambdaTesting.adoc
Add the micronaut-function-aws-test dependency groupId
> docs: add test dependency groupId

- aws-parameter-store/build.gradle
- aws-route53/build.gradle
The upgrade includes a fix for #898
> Upgrade micronaut-discovery-client to 2.2.3

- aws-parameter-store/build.gradle
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfiguration.java
- aws-parameter-store/src/test/groovy/io/micronaut/discovery/aws/parameterstore/AWSPropertyStoreMockConfigurationClientSpec.groovy
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/CredentialsAndRegionFactory.java
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/client/netty/NettyClientConfiguration.java
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/client/netty/NettyClientFactory.java
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/ssm/SsmClientFactory.java
- build.gradle
- examples/aws-parameter-store-example/README.md
- examples/aws-parameter-store-example/build.gradle
- examples/aws-parameter-store-example/gradle.properties
- examples/aws-parameter-store-example/src/main/java/com/example/Application.java
- examples/aws-parameter-store-example/src/main/java/com/example/Owner.java
- examples/aws-parameter-store-example/src/main/java/com/example/OwnerConfiguration.java
- examples/aws-parameter-store-example/src/main/java/com/example/OwnerController.java
- examples/aws-parameter-store-example/src/main/resources/application.yml
- examples/aws-parameter-store-example/src/main/resources/bootstrap.yml
- examples/aws-parameter-store-example/src/main/resources/logback.xml
- examples/aws-parameter-store-example/src/test/groovy/com/example/DemoSpec.groovy
- examples/aws-parameter-store-example/src/test/groovy/com/example/OwnerConfigurationTest.groovy
- function-aws-test/build.gradle
- gradle.properties
- settings.gradle
- src/main/docs/guide/parametersStore.adoc
- src/main/docs/guide/toc.yml
Fixes #899 by using aws sdk 2, where using the BeanCreationEvent the SsmClient retry policy can be configured.
> Use aws-sdk-v2 in aws-parameter-store 

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautRequestReader.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerSpec.groovy
> respect produces media type in controllers

- aws-alexa-httpserver/build.gradle
- aws-alexa/build.gradle
- aws-common/build.gradle
- aws-parameter-store/build.gradle
- aws-route53/build.gradle
- function-aws-alexa/build.gradle
- function-aws-api-proxy-test/build.gradle
- function-aws-api-proxy/build.gradle
- function-aws-custom-runtime/build.gradle
- function-aws-test/build.gradle
- function-aws/build.gradle
- function-client-aws/build.gradle
The root build.gradle already includes micronaut-inject-java as annotationProcessor to every submodule
> build: root includes ann processor mn-inject-java

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautAwsProxyRequestSpec.groovy
close: https://github.com/micronaut-projects/micronaut-aws/issues/1084
> fix: protect against NPE

- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/MicronautLambdaRuntimeSpec.groovy
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
close: https://github.com/micronaut-projects/micronaut-aws/issues/234
> fix: propagate tracing header via system property

- src/main/docs/guide/distributedconfiguration.adoc
- src/main/docs/guide/introduction.adoc
- src/main/docs/guide/lambda/lambdaTesting.adoc
- src/main/docs/guide/lambda/lambdaTutorials.adoc
- src/main/docs/guide/mnawsthree/mnawsthreeBreaks.adoc
- src/main/docs/guide/mnawstwo/mnawstwoBreaks.adoc
- src/main/docs/guide/mnawstwo/mnawstwoWhatsNew.adoc
- src/main/docs/guide/sdkv1/awsCredentialsProvider.adoc
> Fix broken links

- build.gradle
- settings.gradle
- src/main/docs/guide/lambda/lambdaStreamHandler.adoc
- src/main/docs/guide/toc.yml
- test-suite-groovy/build.gradle
- test-suite-groovy/src/test/groovy/io/micronaut/docs/function/aws/EventLogger.groovy
- test-suite-groovy/src/test/groovy/io/micronaut/docs/function/aws/Handler.groovy
- test-suite-groovy/src/test/resources/logback.xml
- test-suite-kotlin/build.gradle
- test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/aws/EventLogger.kt
- test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/aws/Handler.kt
- test-suite-kotlin/src/test/resources/logback.xml
- test-suite/build.gradle
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/ContextFunctionNameSpec.groovy
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/FactoryFunctionBeanSpec.groovy
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautFunctionNameSpec.groovy
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautRequestStreamHandlerOverrideResolveFunctionNameSpec.groovy
- test-suite/src/test/java/io/micronaut/docs/function/aws/CapitalizeFunction.java
- test-suite/src/test/java/io/micronaut/docs/function/aws/EventLogger.java
- test-suite/src/test/java/io/micronaut/docs/function/aws/FunctionsFactory.java
- test-suite/src/test/java/io/micronaut/docs/function/aws/Handler.java
- test-suite/src/test/java/io/micronaut/docs/function/aws/LowerCaseFunction.java
- test-suite/src/test/java/io/micronaut/docs/function/aws/UpperCaseFunction.java
- test-suite/src/test/resources/logback.xml
Close: https://github.com/micronaut-projects/micronaut-aws/issues/1149
> doc: MicronautRequestStreamHandler and @FunctionBean

- function-client-aws/src/main/java/io/micronaut/function/client/aws/AWSInvokeRequestDefinition.java
- function-client-aws/src/test/groovy/io/micronaut/function/client/aws/AwsLambdaInvokeSpec.groovy
Close https://github.com/micronaut-projects/micronaut-aws/issues/1153
> fix: resolve AWSInvokeRequestDefinition name

- src/main/docs/guide/lambda/lambdafunctionclient.adoc
- src/main/docs/guide/toc.yml
- test-suite-groovy/build.gradle
- test-suite-groovy/src/test/groovy/io/micronaut/docs/function/client/aws/AnalyticsClientSpec.groovy
- test-suite-groovy/src/test/groovy/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.groovy
- test-suite-groovy/src/test/groovy/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.groovy
- test-suite-groovy/src/test/resources/application.yml
- test-suite-kotlin/build.gradle
- test-suite-kotlin/src/test/groovy/io/micronaut/docs/function/client/aws/AnalyticsClientSpec.groovy
- test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.kt
- test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.kt
- test-suite-kotlin/src/test/resources/application.yml
- test-suite/build.gradle
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/AnalyticsClientSpec.groovy
- test-suite/src/test/java/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.java
- test-suite/src/test/java/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.java
- test-suite/src/test/resources/application.yml
Closes #1147
see:  https://docs.micronaut.io/1.3.7/guide/#callingFunctions
> doc: Document Lambda invocation via @FunctionClient

- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
Instead annotate with `@Secured(SecurityRule.IS_ANONYMOUS)
see: #1166
> test: don't disable security

- aws-bom/gradle.properties
- build.gradle
Close: https://github.com/micronaut-projects/micronaut-aws/issues/1211
> build: fix docs task

- aws-alexa-httpserver/build.gradle
- aws-alexa/build.gradle
- aws-bom/build.gradle
- aws-common/build.gradle
- aws-distributed-configuration/build.gradle
- aws-parameter-store/build.gradle
- aws-sdk-v1/build.gradle
- aws-sdk-v2/build.gradle
- aws-secretsmanager/build.gradle
- aws-service-discovery/build.gradle
- buildSrc/src/main/groovy/io.micronaut.build.internal.aws-base.gradle
- buildSrc/src/main/groovy/io.micronaut.build.internal.aws-module.gradle
- buildSrc/src/main/groovy/io.micronaut.build.internal.aws-test-suite.gradle
- function-aws-alexa/build.gradle
- function-aws-api-proxy-test/build.gradle
- function-aws-api-proxy/build.gradle
- function-aws-custom-runtime/build.gradle
- function-aws-test/build.gradle
- function-aws/build.gradle
- function-client-aws/build.gradle
- gradle.properties
- settings.gradle
This upgrades to 5.0.2 that fixes the snapshot publish
> build: Gradle build plugin to 5.0.2 and set projectGroup

- gradle.properties
> ci: projectVersion to 3.0.5-SNAPSHOT

- function-aws-api-proxy/build.gradle
- function-aws-custom-runtime/build.gradle
to modules using @TypeHint
CI failed https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/pipelines/458146837/failures
> bug: add back micronaut-graal annprocessor

- test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.kt
- test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.kt
> Fix Kotlin code blocks for @FunctionClient

- gradle.properties
update micronaut test to 3.0.5
> build: micronaut from 3.2.1 to 3.3.4

- aws-alexa-httpserver/build.gradle
- aws-alexa/build.gradle
- aws-common/build.gradle
- aws-distributed-configuration/build.gradle
- aws-parameter-store/build.gradle
- aws-sdk-v1/build.gradle
- aws-sdk-v2/build.gradle
- aws-secretsmanager/build.gradle
- aws-service-discovery/build.gradle
- function-aws-alexa/build.gradle
- function-aws-api-proxy-test/build.gradle
- function-aws-api-proxy/build.gradle
- function-aws-custom-runtime/build.gradle
- function-aws-test/build.gradle
- function-aws/build.gradle
- function-client-aws/build.gradle
- gradle.properties
- gradle/libs.versions.toml
- settings.gradle
Supersedes https://github.com/micronaut-projects/micronaut-aws/pull/1320
~Check-bom is failing 😔~
~I don't declare the aws boms in the catalog as it causes issues, which are under investigation~
Upped to 5.3.2 so boms work 🥳  Thanks @melix
> Settings to 5.3.1 and update build

- gradle.properties
> ci: project version to 3.5.0

- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerStatusSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/StatusSpec.groovy
see: https://github.com/micronaut-projects/micronaut-aws/issues/1387
> test: status httpStatus, response handler

- gradle.properties
githubCoreBranch to 3.6.x
[ci skip]
> ci: project version to 3.6.0-SNAPSHOT

- function-client-aws/src/main/java/io/micronaut/function/client/aws/AWSLambdaFunctionExecutor.java
- function-client-aws/src/test/groovy/io/micronaut/function/client/aws/LocalFunctionInvokeJavaSpec.java
there are no tests for the function lambdas (only 2 are run but are not testing the invocation), if you can point me out how to add one please let me know
> if the return type is void just return null

- src/main/docs/guide/lambda/applicationtyperuntimedependencies.adoc
- src/main/docs/guide/lambda/lambdatriggers.adoc
- src/main/docs/guide/lambda/requestHandlers.adoc
see: https://github.com/micronaut-projects/micronaut-aws/issues/1443
> doc: api-proxy supports only payload 1.0

- src/main/docs/guide/sdkv2/apiGatewayManagementApi.adoc
- src/main/docs/guide/toc.yml
> Documentation for Api Gateway Management API factory beans

- aws-alexa-httpserver/build.gradle.kts
- aws-alexa/build.gradle.kts
- function-aws-alexa/build.gradle.kts
- gradle/libs.versions.toml
- src/main/docs/guide/alexa/skillbuilderprovider.adoc
> Add dependency `com.amazon.alexa:ask-sdk` to the bom

- aws-ua/build.gradle
- aws-ua/src/test/groovy/io/micronaut/aws/ua/UserAgentDisableSpec.groovy
- buildSrc/src/main/groovy/io/micronaut/internal/aws/tasks/UserAgentProviderGeneratorTask.java
- src/main/docs/guide/sdkv2/sdkHttpClient.adoc
> Document user agent

- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyResponseAdapter.java
- function-aws-api-proxy-test/src/test/groovy/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServerSpec.groovy
> Correctly decode mime-encoded byte array

- aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/services/DefaultRequestEnvelopeService.java
- aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/services/RequestEnvelopeService.java
- aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/AlexaSkillBuilder.java
- aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/DefaultAlexaSkillBuilder.java
- aws-alexa/src/main/java/io/micronaut/aws/alexa/conf/AlexaSkillConfigurationProperties.java
- aws-alexa/src/main/java/io/micronaut/aws/alexa/flashbriefing/FlashBriefingItem.java
- aws-alexa/src/test/groovy/io/micronaut/aws/alexa/builders/AlexaSkillBuilderSpec.groovy
- aws-alexa/src/test/groovy/io/micronaut/aws/alexa/flashbriefing/FlashBriefingItemSpec.groovy
- aws-alexa/src/test/java/io/micronaut/aws/alexa/flashbriefing/FlashBriefingsController.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerDontCloseCtxSpec.groovy
- gradle/libs.versions.toml
- settings.gradle.kts
- test-suite-http-server-tck-function-aws-api-proxy/build.gradle.kts
- test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
- Micronaut Gradle Plugin 6.3.5
- Micronaut Framework 4.0.0-M1
- Apache Groovy 4.0.10
- Micronaut Groovy 4.0.0-M1
- Micronaut Serde 2.0.0-M1
- Micronaut Validation 4.0.0-M2
- user jakarta.validation instead of javax.validation
- add validation dependency to tck
- fix http header equal ignore case
- ignore health test
> build: Micronaut Framework M1

- function-aws-api-proxy/build.gradle.kts
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
- gradle/libs.versions.toml
I incorrectly removed it in #1375
> add servlet api dependency back for test

- function-client-aws/src/test/groovy/io/micronaut/function/client/aws/AwsLambdaInvokeSpec.groovy
This reverts commit 4bec11676d60471f6aeb20015cfa1ad304f3001d.
> Revert "add temporary @Ignore"

- function-aws/src/main/java/io/micronaut/function/aws/JsonMapperCustomPojoSerializer.java
see https://github.com/micronaut-projects/micronaut-core/pull/9445
> Workaround Core #9445

- gradle/libs.versions.toml
- test-suite-http-server-tck-function-aws-api-gateway-proxy-alb/src/test/java/io/micronaut/http/server/tck/lambda/tests/ApplicationLoadBalancerTckTestSuite.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv1/src/test/java/io/micronaut/http/server/tck/lambda/tests/FunctionAwsApiGatewayProxyV1HttpServerTestSuite.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv2/src/test/java/io/micronaut/http/server/tck/lambda/tests/FunctionAwsApiGatewayProxyV2HttpServerTestSuite.java
This requires Servlet M10 containing this fix
https://github.com/micronaut-projects/micronaut-servlet/pull/488
> Fix StreamTest TCK test

- function-aws-api-proxy/build.gradle.kts
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/HandlebarsSpec.groovy
- function-aws-api-proxy/src/test/resources/views/home.hbs
Fix handlebars test and stop the merge deleting things
> Merge up 3.18.x

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/security/MicronautLambdaAuthenticationFetcher.java
> NullPointerException in MicronautLambdaAuthenticationFetcher.fetchAuthentication

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload1/ApiGatewayProxyServletResponse.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BinaryContentConfigurationSpec.groovy
> fix: set explicitly base64encoded false

- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/StaticResourceSpec.groovy
- function-aws-api-proxy/src/test/resources/swagger/application.yml
- gradle/libs.versions.toml
> Up to Servlet 4.0.3 and add static-resource test

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MapCollapseUtils.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/alb/ApplicationLoadBalancerServletResponse.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload1/ApiGatewayProxyServletResponse.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload2/APIGatewayV2HTTPResponseServletResponse.java
rename from MapCollapseUtils::getMulitHeaders to MapCollapseUtils::getMultiHeaders
MapCollapseUtils is @Internal
> imp: rename to MapCollapseUtils.getMultiHeaders

- src/main/docs/guide/lambda/customRuntimes.adoc
This addresses the documentation aspect of #1871
> docs: clarify that an implementation of the Micronaut HTTP Client is needed

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/alb/ApplicationLoadBalancerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload1/ApiGatewayProxyEventHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload2/APIGatewayV2HTTPEventHandler.java
ApplicationLoadBalancerRequestEvent and APIGatewayV2HTTPEvent uses Lombok @Data which applies toString https://projectlombok.org/features/Data
APIGatewayProxyRequestEvent overrides toString to render a JSON representation of the object
> Improve logging 

- .editorconfig
- .github/workflows/graalvm-latest.yml
- .github/workflows/gradle.yml
- gradle.properties
- gradle/libs.versions.toml
- settings.gradle.kts
- test-suite-aws-lambda-events/build.gradle.kts
- test-suite-kotlin/build.gradle.kts
- test-suite/build.gradle.kts
Supersedes #1910 to stop micronaut-build force pushing it all the time
> Fix java 21 build

- aws-apigateway/src/main/java/io/micronaut/aws/apigateway/HttpRequestStageResolver.java
- aws-apigateway/src/test/groovy/io/micronaut/aws/apigateway/HttpRequestStageResolverSpec.groovy
- gradle/libs.versions.toml
this is an scenario you could face in testing.
> bug: protect against null context

- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/client/netty/NettyClientConfiguration.java
- aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/client/netty/NettyClientConfigurationSpec.groovy
Close: https://github.com/micronaut-projects/micronaut-aws/issues/1944
> Removing host check. See https://github.com/micronaut-projects/micronaut-aws/issues/1944

- aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/S3ConfigurationSpec.groovy
> Add test to check S3Config can be applied

- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractRequestStreamHandlerMicronautLambdaRuntime.java
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntimeSpec.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/AbstractRequestStreamHandlerMicronautLambdaRuntimeSpec.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/CustomRuntimeForMicronautRequestStreamHandlerSpec.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/FunctionLambdaRuntime.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/FunctionRequestHandler.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/RequestFunction.groovy
- function-aws-custom-runtime/src/test/resources/logback.xml
> fix: handle RequestStreamHandler in AbstractMicronautLambdaRuntime

- src/main/docs/guide/lambda/requestHandlers.adoc
> doc: only abbreviated format is supported

- src/main/docs/guide/distributedconfiguration.adoc
> fix #1116 Add trailing slash to documentation

- aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/LambdaDestinationEventSerde.java
Fixes https://github.com/micronaut-projects/micronaut-aws/issues/2059
> Fix serialization infinite recursion
