micronaut-projects/micronaut-aws

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
- function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandler.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandlerSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/SquareService.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/SquareServiceMockFactory.groovy
Proposed fix for #4, refactoring `MicronautRequestHandler` to allow testing via inject Spock mocks.  Includes a test to demonstrate and verify that the pattern now works.
> Make MicronautRequestHandler friendly to Spock mocks (fixes #4)

- examples/api-gateway-example/README.md
Deleted as part of the move in this commit: https://github.com/micronaut-projects/micronaut-aws/commit/a83dfa2989261bbd0fd852d125104e38925fca2f
Docs point to the readme here: https://github.com/micronaut-projects/micronaut-aws/blob/master/src/main/docs/guide/lambda/apiProxy.adoc
> Add missing README file for API-Gateway example

- function-aws-api-proxy/build.gradle
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FluxSpec.groovy
Otherwise, call `toList()` on the `Flowable`.
Fixes #51
> Check whether the route result is a Single

- .github/workflows/gradle.yml
- aws-common/src/test/resources/logback.xml
- examples/alexa-hello-world-groovy/build.gradle
- examples/alexa-hello-world-groovy/dependency-reduced-pom.xml
- examples/alexa-hello-world-java/dependency-reduced-pom.xml
- examples/alexa-hello-world-java/pom.xml
- examples/api-gateway-example/gradle.properties
- examples/api-gateway-example/settings.gradle
- examples/api-gateway-example/src/main/java/example/StreamLambdaHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ConsumesSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/CookiesSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FiltersSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FluxSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ParametersSpec.groovy
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ResponseStatusSpec.groovy
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/HelloWorldMicronautTest.java
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
- function-aws/src/test/resources/logback.xml
- settings.gradle
- src/main/docs/guide/lambda/apiProxy.adoc
It also has a constructor-based approach for the sample `RequestStreamHandler` implementation. This fixes #36
> Remove deprecated calls

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
Improve AWS Lambda execution time on `MicronautRequestHandler` by moving application context building and handler instance injection into default constructor, which is given more CPU and memory resources comparing to `handleRequest` method. Fixes issue #199
> Improve AWS Lambda execution time for MicronautRequestHandler

- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/RuntimeContext.java
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/RuntimeContextSpec.groovy
Same way LambdaAppender gets hold of LambdaLogger:
https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-log4j2/src/main/java/com/amazonaws/services/lambda/runtime/log4j2/LambdaAppender.java#L28
> Use  LambdaRuntime.getLogger() to get LambdaLogger

- aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/DefaultAlexaSkillBuilder.java
- aws-alexa/src/test/groovy/io/micronaut/aws/alexa/builders/AlexaSkillBuilderSpec.groovy
see: https://github.com/micronaut-projects/micronaut-aws/issues/236
Given an application with two skills configured. 
```yml
alexa:
skills:
helloworld: 
skill-id: 'xxx'   
hellomoon: 
skill-id: 'xxx'   
```
We may have a `LaunchRequest` handler for `helloworld`: 
```java
@Named("helloworld")
@Singleton
public class LaunchRequestHandler implements RequestHandler {
@Override
public boolean canHandle(HandlerInput input) {
return input.matches(Predicates.requestType(LaunchRequest.class));
}
@Override
public Optional<Response> handle(HandlerInput input) {
String speechText = "Welcome to Hello World";
return input.getResponseBuilder()
.withSpeech(speechText)
.build();
}
}
```
And a different `LaunchRequest` handler for `hellomoon`: 
```java
@Named("hellomoon")
@Singleton
public class …
```
> feat: only handlers with same named or unqualified

- function-aws-api-proxy/build.gradle
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
The current implementation only supports JSON inputs as all other content types must be sent in binary format. This PR adds the ability to handle binary requests.
The only problem with this PR is that it seems to me that there is a lack of converters from `byte[]` to other objects. Even automatic conversion from `byte[]` to `String` does not work. But this must be addressed in core libraries, not the AWS one.
> Support for binary requests for the API Gateway

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyExceptionHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautRequestReader.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
Instead of throwing a 500 series server error, allow handling of bad JSON requests,
so that we can return a more appropriate bad request error.
Fixes: #52
The attempt by PR #169 to fix issue #52, miss-understood the problem.  
JSON decoding errors are thrown before ever entering a route, thus this change moves the request body decoding logic into the handler, and makes the exception available to user-defined exception handlers.
> Allow invalid JSON requests to be handled by user defined exception handlers.

- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/client/netty/NettyClientConfiguration.java
- aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/client/NettyClientSpec.groovy
Having a non null Protocol Configuration causes AWS SDK to use proxy
https://github.com/micronaut-projects/micronaut-aws/issues/410
> [Issue/#410] Setting an unconfigured ProtocolConfiguration causes AWS SDK to use proxy

- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServer.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ContextProvider.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyRequestAdapter.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyResponseAdapter.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/MockContextProvider.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServerPort.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServletToAwsProxyRequestAdapter.java
- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServletToAwsProxyResponseAdapter.java
@graemerocher I have split the proxy-test server into multiple beans. 
The goal is to make code a litter easier to process and also to provide users the ability to override certain beans in their test.  
toughts?
> refactor: Split proxy-test into beans

- aws-alexa/build.gradle
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyResponse.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautResponseWriter.java
- gradle.properties
Add missing eager initialization of singletons and configuration in handler used as entry point for apps.
This fix needs https://github.com/micronaut-projects/micronaut-core/issues/4316 which will be included in Micronaut 2.1.2.
In my test application the cold start went from 12 seconds to 9 with this change.
> Initialize eagerly singletons and configuration

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyResponse.java
In #613 I accidentally left `getAllCookies` method public. Reverting it back to package private.
> Make method package protected again

- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterQueryProvider.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/DefaultParameterQueryProvider.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/ParameterQuery.java
- aws-parameter-store/src/test/groovy/io/micronaut/discovery/aws/parameterstore/AWSPropertyStoreMockConfigurationClientSpec.groovy
This PR resolves #657 by adding the ability to declare an `AWSParameterQueryResolver` in cases where the default `/config/application` and `/config/project_name` base paths are undesirable. A package-protected default implementation is provided that preserves the current behaviour.
I also took the liberty to rewrite the very long `getPropertySources()` method in a more pipeline-like fashion, with transformations encapsulated in their own methods.
There is some complexity that is due to the fact that the current implementation uses both `GetParameters` and `GetParametersByPath` AWS API calls to retrieve configuration values. Unless I missed some legacy quirk, a call such as `aws ssm get-parameters --name "/config/application"` doesn't seem to make sense, as it will only return something if …
> Configurable AWS Parameter Store queries

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerSpec.groovy
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
- function-aws-test/build.gradle
- function-aws-test/src/main/java/io/micronaut/function/aws/test/MicronautLambdaJunit5Extension.java
- function-aws-test/src/main/java/io/micronaut/function/aws/test/annotation/MicronautLambdaTest.java
- function-aws-test/src/test/java/io/micronaut/function/aws/test/EagerSingleton.java
- function-aws-test/src/test/java/io/micronaut/function/aws/test/MicronautLambdaExtensionTest.java
- function-aws-test/src/test/resources/logback.xml
- function-aws/src/main/java/io/micronaut/function/aws/LambdaApplicationContextBuilder.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- gradle.properties
- settings.gradle
- src/main/docs/guide/lambda/lambdaTesting.adoc
- src/main/docs/guide/toc.yml
This helps solving https://github.com/micronaut-projects/micronaut-test/issues/330. It basically allows initializing `MicronautRequestHandler`s with the app context from a `@MicronautTest` in this fashion:
```kotlin
@MicronautTest(contextBuilder = [LambdaApplicationContextBuilder::class])
class RequestHandlerTest {
@Inject
lateinit var context: ApplicationContext
@Test
fun testHandler() {
val sampleRequestHandler = SampleRequestHandler(context)
...
```
This is probably still too much work on the user's part. Before going further I'd like this to be validated first.
> Inject preconstructed ApplicationContext in Lambda handler

- aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/controllers/SkillController.java
- aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/exceptions/AskSdkExceptionHandler.java
- aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/exceptions/SecurityExceptionHandler.java
- aws-common/src/main/java/io/micronaut/discovery/cloud/aws/AmazonComputeInstanceMetadataResolver.java
- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
- aws-route53/src/main/java/io/micronaut/discovery/aws/route53/registration/Route53AutoNamingRegistrationClient.java
- aws-route53/src/main/java/io/micronaut/discovery/aws/route53/registration/ServiceRegistrationStatusTask.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/AbstractLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautResponseWriter.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
don't use unnecessary log.isEnabled() checks when using SLF4J, use placeholder replacement
avoid unnecessary toString() when logging
reworked LambdaRuntime logging in AbstractMicronautLambdaRuntime to avoid unnecessary string concatenation
> logging fixes

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
Fixes #761 
The root cause is that when the [ErrorRoute](https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java#L357) is executed, then the decodeBody is called [once again](https://github.com/micronaut-projects/micronaut-aws/blob/f480262e5bbffd0a5e63c7cadfc74203859ea244/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java#L511), what fails, because the request doesn't contain json node, but already decoded object. 
Fixes #208  
Fixes #136
> fix failure when body was already decoded

- aws-parameter-store/build.gradle
- aws-route53/build.gradle
- function-aws-api-proxy/build.gradle
delete annotationProcessor micronaut-graal from subprojects because it is already applied to every subproject at root build file.
> build: root already adds ann micronaut-graal

- aws-sdk-v2/build.gradle
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/secretsmanager/SecretsManagerClientFactory.java
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/secretsmanager/package-info.java
- aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/SecretsManagerClientSpec.groovy
- gradle.properties
- src/main/docs/guide/sdkv2/secretsmanager.adoc
- src/main/docs/guide/toc.yml
see: https://github.com/micronaut-projects/micronaut-aws/issues/1006
see: https://aws.amazon.com/secrets-manager/
> feat: add secrets manager client factory

- src/main/docs/guide/lambda/objectmapperconfiguration.adoc
- src/main/docs/guide/toc.yml
This recovers this snippet of documentation which was introduced here:
https://github.com/micronaut-projects/micronaut-aws/pull/195/files
and accidentally deleted here:
https://github.com/micronaut-projects/micronaut-aws/pull/471
> doc: Object Mapper Configuration

- function-aws-alexa/src/main/java/io/micronaut/function/aws/alexa/AlexaFunction.java
- function-aws-api-proxy/build.gradle
- function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
- function-client-aws/src/test/groovy/io/micronaut/function/client/aws/LocalFunctionInvokeSpec.groovy
- gradle.properties
- replace ApplicationContext.:build with ctx::builder
- bump up micronaut to 3.0.0-M5
- bump up micronaut test 3.0.0-RC2
- remove @PendingFeature
- don't specify views version
- build:del property micronautDiscoveryClientVersion
Close: https://github.com/micronaut-projects/micronaut-aws/pull/1138/files
> build: bump up to Micronaut 3.0.0-M5

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- src/main/docs/guide/lambda/lambdaStreamHandler.adoc
- src/main/docs/guide/mnawsthree/mnawsthreeBreaks.adoc
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/ContextFunctionNameSpec.groovy
- test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautFunctionNameSpec.groovy
Property `micronaut.function.name` takes precedence over the function name present in the Lambda Context.
I consider the current default probably a bug. Since the Lambda Context Function name is "always" present.  Because of that, I have swapped the precedence for the next mayor version of Micronaut AWS.
> BREAKING CHANGE: micronaut.function.name precedence

- function-aws/build.gradle
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerDontCloseCtxSpec.groovy
> Don't close application context between requests in MicronautRequestStreamHandler

- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AwsLambdaRuntimeApi.java
An update to the AbstractMicronautLambdaRuntime and AwsLambdaRuntimeApi to send the version of Java and the version of Micronaut as the user-agent information in the HTTP request header.
> Send a user-agent header with requests to the Lambda Runtime API.

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaHandler.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/LambdaContextSpec.groovy
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
- function-aws/src/main/java/io/micronaut/function/aws/DefaultDiagnosticInfoPopulator.java
- function-aws/src/main/java/io/micronaut/function/aws/DefaultLambdaContextFactory.java
- function-aws/src/main/java/io/micronaut/function/aws/DiagnosticInfoPopulator.java
- function-aws/src/main/java/io/micronaut/function/aws/HandlerUtils.java
- function-aws/src/main/java/io/micronaut/function/aws/LambdaContextFactory.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- function-aws/src/main/java/io/micronaut/function/aws/XRayUtils.java
- function-aws/src/test/groovy/io/micronaut/function/aws/LambdaContextSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/MappingDiagnosticContextSetterSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautStreamHandlerLambdaContextSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandler.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandlerSpec.groovy
- src/main/docs/guide/lambda/lambdacontext.adoc
- src/main/docs/guide/toc.yml
Fixes: https://github.com/micronaut-projects/micronaut-aws/issues/1332
Fixes: https://github.com/micronaut-projects/micronaut-aws/issues/1326
This is first attempt to generalize adding diagnostic information to lambda handler despite significant difference between `MicronautRequestHandler` and `MicronautLambdaHandler`. See also #1287 
I'll update documentation and add test when receive a green light for choosen approach.
@graemerocher and @sdelamo your comments are welcome especially regarding bean initialization and registration.
> Register Lambda Context as singletons and MDC for every Handler

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
When using AWS and OAuth 2.0 I get the following exception
```
java.lang.NullPointerException: null
at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getBody(MicronautAwsProxyRequest.java:279)
at io.micronaut.security.oauth2.client.ClientUtils.getResponseData(ClientUtils.java:36)
at io.micronaut.security.oauth2.client.DefaultOpenIdClient.onCallback(DefaultOpenIdClient.java:130)
```
> fix: Only attempt to decode base64 if body != null

- function-aws-api-proxy-test/src/test/groovy/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServerSpec.groovy
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ParametersSpec.groovy
Fix for the issue with duplicate decoding of query parameters arriving from Api Gateway proxy (https://github.com/micronaut-projects/micronaut-aws/issues/1407).
Results from testing the changes on AWS (Aws Api Gateway Lambda proxy integration):
`curl https://<AWS_GATEWAY_API_URL_PREFIX>.execute-api.us-east-1.amazonaws.com/test/mypath?testparam=aa%2Bbb
{"testparam":"aa+bb"}`
> Duplicate decoding of query parameters arriving from Api Gateway proxy

- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/s3/S3ClientFactory.java
- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/s3/S3ConfigurationProperties.java
- aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/S3ClientSpec.groovy
Overriding the S3 endpoint is required when using services such as Localstack, or when using an S3 client for any S3-compatible storage service.
Before this change, users would need to implement a `BeanCreatedEventListener` to programmatically set the endpoint. This PR allows setting the endpoint via configuration
> Allow overriding the endpoint via configuration

- aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/s3/S3ClientFactory.java
For the S3Client the override property worked, but not for the S3AsyncClient. This PR should fix that.
Now you will be able to override the S3 endpoint with
````
aws:
s3:
endpoint-override: http://localhost:4566
````
This can also be linked to https://github.com/micronaut-projects/micronaut-aws/issues/790 and https://github.com/micronaut-projects/micronaut-aws/pull/831
> Fix endpoint override for S3Async Client

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
In case of using an external system to monitor errors such as Sentry there is currently no way how to forward context creation errors into the system. 
When there is an issue with the `ApplicationContext` such as missing property then the errors are only logged into CloudWatch which is not sufficient.
Logging the errors in the constructor where they initialization happens is the best way how to keep track of these issues.
> Log context initialization errors

- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/MicronautLambdaRuntimeSpec.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/RuntimeApiSpec.groovy
- function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/TracingHeaderPropagationSysPropertySpec.groovy
- gradle.properties
I had to dowgrade to 3.5.5 
because the Body string received with `3.6.2` here:
```java
@Post("/2018-06-01/runtime/invocation/{requestId}/response")
HttpResponse<?> response(@PathVariable("requestId") String requestId, @Body String body) {
```
is : 
` PooledSlicedByteBuf(ridx: 0, widx: 156, cap: 156/156, unwrapped: PooledUnsafeDirectByteBuf(ridx: 364, widx: 364, cap: 2048))`
@yawkat any idea what could be the culprit?
> fix: test with APIGatewayProxy

- src/main/docs/guide/sdkv2/s3.adoc
> Cross reference to Micronaut Object Storage

- aws-sdk-v2/src/main/resources/META-INF/native-image/io.micronaut.aws/micronaut-aws-sdk-v2/reflect-config.json
Can be removed once https://github.com/aws/aws-sdk-java-v2/pull/3428 is released.
> Add necessary GraalVM configuration for the Apache HTTP client

- aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfiguration.java
This PR fixes a typo in the javadoc of `AWSParameterStoreConfiguration. setUseSecureParameters(boolean)`.
> Fix KMS typo in javadoc of parameter store config

- aws-cloudwatch-logging/src/main/java/io/micronaut/aws/cloudwatch/logging/CloudWatchLoggingClient.java
- aws-cloudwatch-logging/src/test/groovy/io/micronaut/aws/cloudwatch/logging/CloudWatchLoggingAppenderSpec.groovy
- aws-cloudwatch-logging/src/test/groovy/io/micronaut/aws/cloudwatch/logging/CloudwatchLoggingSpec.groovy
This PR removes unnecessary dependency to microanut-descovery module from AWS Cloud Logging.
> Remove discovery dependency from AWS logging

- aws-sdk-v2/src/main/resources/META-INF/native-image/io.micronaut.aws/micronaut-aws-sdk-v2/reflect-config.json
When a native image micronaut service is running in AWS kubernetes cluster, the GetParameters and ListSecrets AWS requests fail because AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN environment variables are not used for authentication. Those env variables are not used because `software.amazon.awssdk.auth.credentials.internal.WebIdentityCredentialsUtils` class is using reflection to load and create an instance of `software.amazon.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory` class. The issue can be seen here too:
```
https://github.com/aws/aws-sdk-java-v2/issues/2985
```
> graal: StsWebIdentityCredentialsProviderFactory class is loaded via reflection

- aws-cloudwatch-logging/build.gradle.kts
- aws-distributed-configuration/build.gradle.kts
- aws-parameter-store/build.gradle.kts
- aws-sdk-v2/build.gradle.kts
- aws-service-discovery/build.gradle.kts
- buildSrc/src/main/groovy/io.micronaut.build.internal.aws-base.gradle
- config/checkstyle/checkstyle.xml
- function-aws-api-proxy/build.gradle.kts
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/AwsRequestLifecycle.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyResponse.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautRequestReader.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/VersionSpec.groovy
- function-aws-custom-runtime/build.gradle.kts
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
- function-aws-test/build.gradle.kts
- function-aws/build.gradle.kts
- function-client-aws/build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
Untested, can't get the snapshot to run locally. Most of the code that I removed seems to be identical with RouteExecutor (or, now, RequestLifecycle), however I may have missed some differences.
> Use new RequestLifecycle api

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
Native executable was failing in AWS Lambda with:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.amazonaws.serverless.proxy.model.SingleValueHeaders` (no Creators, like default constructor, exist): no default constructor found
```
> fix: graal typehint for SingleValueHeaders

- function-aws-api-proxy/build.gradle.kts
exclude `slf4j-api` from `com.amazonaws.serverless:aws-serverless-java-container-core`
Since version `1.9` it was pulling` slf4j-api` `2.0.6`
Close https://github.com/micronaut-projects/micronaut-aws/issues/1560
> build: exclude slf4j-api from aws-serverless

- aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfiguration.java
- aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationClient.java
- aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationProperties.java
- aws-distributed-configuration/src/test/groovy/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationSpec.groovy
I would like to suggest an addition to support multiple prefixes for micronaut AWS distributed configuration. The change is not breaking and the previous remains the same if the prefixes property is not set. 
The need it fulfills is the situation where the configuration has to be read from multiple secrets that do not share a common prefix. 
Let me know what you think.
> Support multiple prefixes for aws distributed configuration 

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
- gradle/libs.versions.toml
- test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
When the filter blocks access to localhost from a non-local origin, there is no ROUTE_INFO set on the response object.
Previously, we just called get() on the Optional.  This fails.
I believe the fix is to only continue processing the response if the ROUTE_INFO has been applied to the response.
> Fix for drive-by localhost cors deny TCK test

- src/main/docs/guide/alexa/alexaskillconfiguration.adoc
- src/main/docs/guide/distributedconfiguration/distributedconfigurationsecretsmanager.adoc
- src/main/docs/guide/distributedconfiguration/parametersStore.adoc
- src/main/docs/guide/lambda/lambdafunctionclient.adoc
- src/main/docs/guide/sdkv2/awsCredentials.adoc
- src/main/docs/guide/sdkv2/awsRegionSelection.adoc
> Migrate to new configuration asciidoc macro

- aws-secretsmanager/src/main/java/io/micronaut/aws/secretsmanager/SecretsManagerKeyValueFetcher.java
- aws-secretsmanager/src/test/groovy/io/micronaut/aws/secretsmanager/SecretsManagerKeyValueFetcherSpec.groovy
This PR aims to resolve GH-1442. I implemented the approach based on gracefully handling and logging all issues that might happen when fetching secrets from AWS Secrets Manager. There are little code changes that IMO do the job. However, the proposed solution based on modifying configuration properties to fetch only specified secrets is still an option. Looking forward for your feedback
> GH-1442: Handle SecretsManagerException thrown when fetching secrets

- test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/LambdaServerUnderTest.java
- test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
We need to decode base64 responses in the test harness
> Fix the Octet test

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
- test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
This allows the client filter TCK tests that mutate the request to pass.
The Cookies were effectively mutable already (as they were simple cookies)
To make parameters and headers mutable, I updated the Aws variants
> TCK: Add a mutable version of MicronautAwsProxyRequest

- aws-cloudwatch-logging/src/main/java/io/micronaut/aws/cloudwatch/logging/CloudWatchLoggingAppender.java
- aws-cloudwatch-logging/src/test/groovy/io/micronaut/aws/cloudwatch/logging/CloudWatchLoggingAppenderSpec.groovy
- Postpone the dispatch thread creation to runtime. Start the thread to send logs to cloudwatch only when `append` method is called, instead of `start`. This way the thread is not started during build time, which is unsupported by native image. (See #1687 for details).
- Create `dispatchOnStart` property to return to previous behavior if needed.
> #1687 Fix native image build with CloudWatchLoggingAppender

- aws-cloudwatch-logging/src/test/groovy/io/micronaut/aws/cloudwatch/logging/CloudwatchLoggingSpec.groovy
- function-aws-test/src/main/java/io/micronaut/function/aws/test/MicronautLambdaJunit5Extension.java
- function-aws-test/src/main/java/io/micronaut/function/aws/test/annotation/MicronautLambdaTest.java
- gradle/libs.versions.toml
- test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
AWS 3.17.x uses [an internal class of Micronaut Test which which was changed for 3.9.x](https://github.com/micronaut-projects/micronaut-test/commit/d21d26e4a509e785250e2b50bef1a14a80c6d2b6]. This PR update 3.17.x the branch which ships with 3.9.x to fix the breaking change. 
Close: #1742
- Updates Micronaut Framework 3.9.2
- Ignore failing tests in tck
> fix: Micronaut Lambda Test compilation with 3.9.2

- aws-cloudwatch-logging/src/main/java/io/micronaut/aws/cloudwatch/logging/CloudWatchLoggingClient.java
When the cloudwatch logs client bean is getting destroyed, it can throw NPE. If there is no cw logs appender used.
Added null check before closing to eliminate case of NPE, for use-case CW Logs Client is used apart from logging use-cases.
> fix: closing static logging client

- aws-cloudwatch-logging/build.gradle.kts
When we exclude a dependency, this will end up in the POM.
For Maven to consume this, we should specify both the group and module.
This then ends up in the POM as
```
<dependency>
<groupId>ch.qos.logback.contrib</groupId>
<artifactId>logback-json-classic</artifactId>
<version>0.1.5</version>
<scope>runtime</scope>
<exclusions>
<exclusion>
<artifactId>logback-classic</artifactId>
<groupId>ch.qos.logback</groupId>
</exclusion>
</exclusions>
</dependency>
```
> Exclude module as well as just group

- function-aws-custom-runtime/build.gradle.kts
- function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
To solve errors when deploying a GraalVM Native Image with jackson databind to a Lambda custom runtime. 
```
io.micronaut.http.client.exceptions.HttpClientResponseException: 
Error decoding HTTP response body: 
Error decoding JSON stream for type [APIGatewayProxyRequestEvent]: 
Cannot construct instance of `com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent`: 
cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
```
> graal: more TypeHint.AccessTypes for Lambda Events

- aws-lambda-events-serde/build.gradle.kts
- function-aws/build.gradle.kts
- function-aws/src/main/java/io/micronaut/function/aws/CustomPojoSerializerException.java
- function-aws/src/main/java/io/micronaut/function/aws/JsonMapperCustomPojoSerializer.java
- function-aws/src/main/resources/META-INF/services/com.amazonaws.services.lambda.runtime.CustomPojoSerializer
- function-aws/src/test/groovy/io/micronaut/function/aws/JsonMapperCustomPojoSerializerSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestHandlerSpec.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerSpec.groovy
- function-aws/src/test/resources/api-gateway-proxy.json
- src/main/docs/guide/lambda/customPojoSerialization.adoc
- src/main/docs/guide/mnawsfour.adoc
- src/main/docs/guide/mnawsfour/mnawsfourBreaks.adoc
- src/main/docs/guide/toc.yml
This PR modifies `micronaut-function-aws` to provide an implementation of `com.amazonaws.services.lambda.runtime.CustomPojoSerializer` which is loaded via SPI. This `CustomPojoSerialization` avoids your Micronaut function to pay a double hit on performances when using a serialization library inside the Lambda function.
> feat: Add CustomPojoSerializer

- aws-sdk-v2/src/main/resources/META-INF/native-image/io.micronaut.aws/micronaut-aws-sdk-v2/reflect-config.json
Metadata entry for StsWebIdentityCredentialsProviderFactory has been added to awssdk:sts library:
`https://github.com/aws/aws-sdk-java-v2/blob/2.20.80/services/sts/src/main/resources/META-INF/native-image/software.amazon.awssdk/sts/reflect-config.json`
so we don't need it anymore in micronaut-aws
> Deleted unnecessary AWS STS metadata

- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv1/src/test/java/io/micronaut/http/server/tck/lambda/APIGatewayProxyRequestEventFactory.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv1/src/test/java/io/micronaut/http/server/tck/lambda/GatewayLambdaServerUnderTest.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv1/src/test/java/io/micronaut/http/server/tck/lambda/tests/FunctionAwsApiGatewayProxyV1HttpServerTestSuite.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv2/src/test/java/io/micronaut/http/server/tck/lambda/APIGatewayV2HTTPEventFactory.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv2/src/test/java/io/micronaut/http/server/tck/lambda/GatewayLambdaServerUnderTest.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv2/src/test/java/io/micronaut/http/server/tck/lambda/tests/FunctionAwsApiGatewayProxyV2HttpServerTestSuite.java
None of our other TCK tests POST a POJO as a body (we usually craft json as a string).
This picked up that our conversion factory method (to convert it to an AWS event wasn't correctly converting the body back to Json if a POJO was sent.
Closes #1764
> Fix MissingBodyAnnotation TCK test

- function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServer.java
- test-suite-http-server-tck-function-aws-api-proxy-test/build.gradle.kts
- test-suite-http-server-tck-function-aws-api-proxy-test/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
- test-suite-http-server-tck-function-aws-api-proxy-test/src/test/resources/application.yml
We had two issues here.
1. We needed to switch off the AWS health status (as with the other TCK tests)
To do this, we use a property in a yaml file
2. When we ran the tests we have 2 application contexts.
One of them is in the Lambda handler -- this is the one we want
The other is in the test-server -- this is the one we don't want
Tests were failing as we were using beans from one in the test, and then beans from the other in the assertion.
Fixed by returning the handler application context from the test-server
> Fix the AWS tck-function-aws-api-proxy-test tests

- config/accepted-api-changes.json
I have no idea why we need to do this change. we have not changed this file https://github.com/micronaut-projects/micronaut-aws/commits/master/aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/CognitoUserPoolMigrateUserEventSerde.java
> accept api changes for serde import introspections

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/ApiGatewayServletRequest.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/alb/ApplicationLoadBalancerServletRequest.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload1/ApiGatewayProxyServletRequest.java
- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload2/APIGatewayV2HTTPEventServletRequest.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-alb/src/test/java/io/micronaut/http/server/tck/lambda/tests/RequestUriContainsQueryValueTest.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv1/src/test/java/io/micronaut/http/server/tck/lambda/tests/RequestUriContainsQueryValueTest.java
- test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv2/src/test/java/io/micronaut/http/server/tck/lambda/tests/RequestUriContainsQueryValueTest.java
- test-suite-http-server-tck-function-aws-api-proxy-test/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
- test-suite-http-server-tck-function-aws-api-proxy-test/src/test/java/io/micronaut/http/server/tck/lambda/tests/RequestUriContainsQueryValueTest.java
see: https://github.com/micronaut-projects/micronaut-aws/issues/1848
I added the same test to the core TCK I have added a test in the TCK https://github.com/micronaut-projects/micronaut-core/pull/9791
> fix: request.getUri should respond include path and query values

- function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/ApiGatewayServletRequest.java
- function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/payload1/ApiGatewayProxyServletRequestSpec.groovy
Close: https://github.com/micronaut-projects/micronaut-aws/issues/1864
> fix: protect against null path

- src/main/docs/guide/lambda/requestHandlers.adoc
The packages `micronaut-function-aws` and `micronaut-function-aws-api-proxy` are part of the group `io.micronaut.aws` and not `io.micronaut`.
> docs: fix dependency for lambda handlers

- function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
- function-aws/src/test/groovy/io/micronaut/function/aws/ContextUtils.groovy
- function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerStartsContextSpec.groovy
Close: #1913
This PR changes so the MicronautRequestStreamHandler constructor starts the application context, and it invokes `inject(this)` for the handler to resolve injection points.
> fix: start context in MicronautRequestStreamHandler

- test-suite-aws-lambda-events-serde/build.gradle.kts
- test-suite-aws-lambda-events-serde/src/test/java/io/micronaut/aws/lambda/events/serde/tests/Issue2056Test.java
When we add back `@SerdeImport(Object.class)` to aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/LambdaDestinationEventSerde.java, this test fails.
> Add test for issue 2056

- aws-lambda-events-serde/build.gradle.kts
- aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/SerdeCustomPojoSerializer.java
- aws-lambda-events-serde/src/main/resources/META-INF/services/com.amazonaws.services.lambda.runtime.CustomPojoSerializer
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/APIGatewayCustomAuthorizerEventSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/APIGatewayProxyRequestEventSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/AllAwsLambdaEventsSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/CloudFrontSimpleRemoteCallSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/CloudWatchLogsEventSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/CodeCommitRepositoryEventSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/CognitoEventSerdeSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/CustomPojoSerializerUtils.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/DynamodbEventSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/S3EventNotificationSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/SQSReceiveMessageSpec.groovy
- aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/SerializeMapsAndCollectionsSpec.groovy
- function-aws/src/main/java/io/micronaut/function/aws/JsonMapperCustomPojoSerializer.java
Add a CustomPojoSerializer implementation which includes the package io.micronaut.aws.lambda.events.serde. This package contains `@SerdeImport` for the AWS Lambda Events classes.
Close: https://github.com/micronaut-projects/micronaut-aws/issues/2048
> fix: CustomPojoSerializer adds lambda events pkg
